export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS';
export const EMPTY_COMPANY_DETAILS = 'EMPTY_COMPANY_DETAILS';
export const COMPANY_FLAG='COMPANIES';