export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const EMPTY_PRODUCT_DETAILS = 'EMPTY_PRODUCT_DETAILS';
export const PRODUCT_FLAG='PRODUCTS';